## Introduction to Numpy

#### **Name:** <Insert name>


#### Import numpy

In [1]:
import numpy as np

#### Numpy operations
1.- Create array a with values from 1-5 \
2.- create an array b with values from 6 - 10

In [4]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [5]:

b = np.arange(6, 11)
b

array([ 6,  7,  8,  9, 10])

#### Matrix Operations with numpy

1. Create a 3x3 matrix in numpy with the following values: 

⎡ 1  2  3 ⎤ \
⎢ 4  5  6 ⎥ \
⎣ 7  8  9 ⎦ 

2.- Transpose the matrix and save it into a transpose variable \
3.- Add both matrix \
4.- Multiply both matrix



In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
transpose = matrix.T
transpose


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
add = matrix+transpose
add

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

In [10]:
multiply = matrix@transpose
multiply

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

#### numpy indexing

1.- Create a numpy array [10, 20, 30, 40, 50, 60] \
2.- print second and last index \
3.- print elements 1-3 \
4.- print all but the first 2 elements \
5.- reshape the array to be a 2x3 matrix 

In [11]:
arr = np.array([10, 20, 30, 40 , 50, 60])
arr

array([10, 20, 30, 40, 50, 60])

In [12]:
arr[1]

np.int64(20)

In [13]:
arr[-1]

np.int64(60)

In [16]:
arr[:3]

array([10, 20, 30])

In [19]:
arr[2:]

array([30, 40, 50, 60])

In [17]:
arr.reshape(2, 3)

array([[10, 20, 30],
       [40, 50, 60]])

#### Creating random arrays
1- Create a 3x3 matrix with random numbers. \
2.- Create a 2x3 matrix with random integers.


In [20]:
random_arr = np.random.rand(3, 3)
random_arr

array([[0.34364208, 0.94869033, 0.42059536],
       [0.14013339, 0.62763472, 0.19451742],
       [0.35739315, 0.32869227, 0.96837148]])

In [22]:
random_arr_int = np.random.randint(0, 10, size=(2, 3))
random_arr_int

array([[0, 8, 3],
       [0, 8, 9]], dtype=int32)

#### Boolean Indexing and Filtering
1.- Generate a random dataset in a 5x5 matrixs filled with integers from 1-50. \
2.- Filter the values that are bigger than 25 and replace them with 0. \
3.- Calculate the basic statisticañ dispersion and tendency meassurements.

In [23]:
dataset = np.random.randint(1, 50, size=(5, 5))
dataset

array([[34, 42, 30, 44, 49],
       [25,  9,  6, 49, 22],
       [34, 45, 45, 44, 22],
       [42, 19,  9, 23, 43],
       [44, 40, 39,  1,  4]], dtype=int32)

In [24]:
dataset[dataset > 25] = 0
dataset

array([[ 0,  0,  0,  0,  0],
       [25,  9,  6,  0, 22],
       [ 0,  0,  0,  0, 22],
       [ 0, 19,  9, 23,  0],
       [ 0,  0,  0,  1,  4]], dtype=int32)

In [25]:
np.std(dataset)

np.float64(8.749857141690942)

In [26]:
np.mean(dataset)

np.float64(5.6)

In [27]:
np.median(dataset)

np.float64(0.0)

In [28]:
np.var(dataset)

np.float64(76.55999999999999)

#### Homework exercise numpy

⎡ 2  3 ⎤ \
⎣ 0  1 ⎦ 


⎡ 1  2 ⎤  
⎣ 4  0 ⎦ 

1. The product
2. Product's transpose.
3. Determinant of the product
4. The inverse of the product.

In [32]:
A = np.array([[1, 3], [0, 1]])
B = np.array([[1, 2], [4, 0]])
A

array([[1, 3],
       [0, 1]])

In [33]:
C = A @ B
C

array([[13,  2],
       [ 4,  0]])

In [34]:
transpose = C.T
transpose

array([[13,  4],
       [ 2,  0]])

In [36]:
determinate = np.linalg.det(C)
determinate

np.float64(-8.000000000000002)

In [37]:
inverse = np.linalg.inv(C)
inverse

array([[ 0.   ,  0.25 ],
       [ 0.5  , -1.625]])